language: cpp
sudo: required

compiler:
- clang
- gcc

env:
- QT_BASE=53
- QT_BASE=54
- QT_BASE=55

matrix:
  allow_failures:
  - compiler: clang
    env: QT_BASE=53
  - compiler: clang
    env: QT_BASE=55

before_install:
#- if [ "$CXX" = "g++" ]; then sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y; fi
- if [ "$QT_BASE" = "53" ]; then sudo add-apt-repository ppa:beineri/opt-qt532 -y; fi
- if [ "$QT_BASE" = "54" ]; then sudo add-apt-repository ppa:beineri/opt-qt541 -y; fi
- if [ "$QT_BASE" = "55" ]; then sudo add-apt-repository ppa:beineri/opt-qt55 -y; fi
- sudo apt-get update -qq

install:
- if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.9 gcc-4.9; export CXX="g++-4.9" CC="gcc-4.9"; $CXX --version; fi
- sudo apt-get install -qq qt${QT_BASE}base; source /opt/qt${QT_BASE}/bin/qt${QT_BASE}-env.sh

script:
- qmake -r "QMAKE_CXX=$CXX" "QMAKE_CC=$CC" "QMAKE_LINK=$CXX"
- make check

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    - gcc-4.9
    - g++-4.9
    - clang-3.6
